// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyConmBpLZbbPAhbyNKX64dZVPK0WlfaRYc',
    appId: '1:194557032777:web:8a24f08612dbca9bd18298',
    messagingSenderId: '194557032777',
    projectId: 'chat-app-f3f06',
    authDomain: 'chat-app-f3f06.firebaseapp.com',
    storageBucket: 'chat-app-f3f06.firebasestorage.app',
    measurementId: 'G-K17D872R2Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxFOnqcNXePETWpwaLgWhS4SGAFf--lNA',
    appId: '1:194557032777:android:d8eae2807abba462d18298',
    messagingSenderId: '194557032777',
    projectId: 'chat-app-f3f06',
    storageBucket: 'chat-app-f3f06.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH6xI7PqykYTVXy4MlWk10mU0kQ4VANI0',
    appId: '1:194557032777:ios:fd081964f21fb3c2d18298',
    messagingSenderId: '194557032777',
    projectId: 'chat-app-f3f06',
    storageBucket: 'chat-app-f3f06.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDH6xI7PqykYTVXy4MlWk10mU0kQ4VANI0',
    appId: '1:194557032777:ios:fd081964f21fb3c2d18298',
    messagingSenderId: '194557032777',
    projectId: 'chat-app-f3f06',
    storageBucket: 'chat-app-f3f06.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyConmBpLZbbPAhbyNKX64dZVPK0WlfaRYc',
    appId: '1:194557032777:web:c3ac46f4929faad8d18298',
    messagingSenderId: '194557032777',
    projectId: 'chat-app-f3f06',
    authDomain: 'chat-app-f3f06.firebaseapp.com',
    storageBucket: 'chat-app-f3f06.firebasestorage.app',
    measurementId: 'G-5LK9LBGKZ1',
  );
}
